#!/bin/bash

# todo: improve the trap
trap exit ERR

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/config
source ${AH_DIR}/build_httpd
source ${AH_DIR}/build_php
source ${AH_DIR}/build_yaf_ext
source ${AH_DIR}/build_phalcon_ext
source ${AH_DIR}/build_mongo_driver

check_httpd
check_php
check_yaf_ext # php extension
check_phalcon_ext # php extension
check_mongo_driver # php db driver
