#!/bin/sh

# The logic to stop your application should be put in this script.

. ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/config

if [ -e "${ROOT_DIR}/httpd/bin/apachectl" ]; then
	echo "Stopping httpd"
	${ROOT_DIR}/httpd/bin/apachectl graceful-stop
fi

if [ -e "${ROOT_DIR}/php/var/run/php-fpm.pid" ]; then
	echo "Stopping php-fpm"
	kill -s 3 `cat ${ROOT_DIR}/php/var/run/php-fpm.pid`
fi

# check, if there is really no httpd and php-fpm process
sleep 5
if pgrep httpd > /dev/null; then
	echo "Killing httpd"
	kill -s 9 `pgrep httpd` || true
fi

if pgrep php-fpm > /dev/null; then
	echo "Killing php-fpm"
	kill -s 9 `pgrep php-fpm` || true
fi
